language: csharp
solution: UsersDhi.sln
mono: none
dotnet: 2.0.0
notifications:
  email: false
services:
- mysql
- docker
script:
- dotnet restore
- cd IntegrationTests
- dotnet test
- cd ..
- cd UsersDhi
deploy:
 provider: script
 skip_cleanup: true
 script: sh ./deploy.ssh $DOCKER_USERNAME $DOCKER_PASSWORD $APP_NAME