language: csharp
solution: WebApplication1.sln
mono: none
dotnet: 2.0.0
notifications:
  email: false
services:
- mysql
- docker
script:
- dotnet restore
- cd UnitTestProject1
- dotnet test
- cd ..
- cd WebApplication1
- dotnet publish 
- docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD" registry.heroku.com
- docker build -t aspnet-on-heroku ./bin/Debug/netcoreapp1.1/publish
- docker tag aspnet-on-heroku registry.heroku.com/$APP_NAME/web
- docker push registry.heroku.com/$APP_NAME/web