language: csharp
solution: WebApplication1.sln
mono: none
dotnet: 2.0.0
notifications:
  email: false
services:
- mysql
script:
- dotnet restore
- cd UnitTestProject1
- dotnet test
before_deploy:
- cd ..
- cd WebApplication1