language: csharp
solution: WebApplication1.sln
mono: none
dotnet: 2.0.0
notifications:
  email: false
services:
- mysql
- docker
script:
- dotnet restore
- cd UnitTestProject1
- dotnet test
- cd ..
- cd WebApplication1
- dotnet publish 
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker build -t aspnet-on-heroku ./bin/Debug/netcoreapp1.1/publish
- docker tag aspnet-on-heroku $REGISTRY_URL
- docker push $REGISTRY_URL